### ISSUE TITLE
How to use a specific krangl version in Jupiter with Kotlin kernel? 

### ISSUE THREAD

**Issue by alshan** [holgerbrandl/krangl#119]
```
%use krangl(0.15.7)
```

results in error: 
> Failed to resolve com.github.holgerbrandl:krangl:0.15.7:
File 'com.github.holgerbrandl:krangl:0.15.7' not found
unresolved dependency: com.github.holgerbrandl#krangl;0.15.7: not found

**Comment by LeandroC89** [comment]
Hello Igor,
You're using it right as that is how I use it too, however the latest version I'm able to use is 0.15.3, not sure it'll have everything you need but it is working nicely.

`%use krangl(0.15.3)`

From 0.15.4 upwards I've faced the same issue you did

**Comment by alshan** [comment]
I see, thank you!

**Comment by holgerbrandl** [comment]
Since jcenter is going down, I moved krangl to maven-central. This required to change the group-id from de.mpicbg.scicomp to `com.github.holgerbrandl.krangl`, which is subsequently simplified to `com.github.holgerbrandl.krangl` (starting with 0.15.8). 

This should fix jupyter usage with the current definition https://github.com/Kotlin/kotlin-jupyter/blob/master/libraries/krangl.json with 0.15.8 and higher. If not I'll prepare a PR on the file to fix it.

I'm not able to port all old versions from jcenter to maven-central unfortunately. Sorry for that.

**Comment by LeandroC89** [comment]
Thanks, it worked for me with 0.15.8
