### ISSUE TITLE
Consider more efficient csv parsers

### ISSUE THREAD

**Issue by deviant-studio** [holgerbrandl/krangl#62]
I believe `Krangl` is useful for big datasets processing. So parsing huge csv files may be a bottle neck.
Based on this resource https://github.com/uniVocity/csv-parsers-comparison `commons-csv` is one of the slowest parsers in the world :) Maybe it's make sense to migrate to more efficient lib like Univocity?

**Comment by holgerbrandl** [comment]
Hey, that's an excellent pointer. I wasn't aware of neither the benchmark nor the _winner_. I'm trying to integrate it (which seems straightforward) and will do some benchmark on my own.

**Comment by holgerbrandl** [comment]
I've considered it

, but the data is not supporting such an effort:
```
A DataFrame: 2 x 5
            config      mean        sd
1   apache_commons   964.417    73.709
2        univocity    834.81   258.672
```
Data was acquired by reading a 330k tsv-table (flightsData) with warmup and 20 repetitions.
Not sure how if I'm doing it wrong, but the performance difference is imho negligible. At least at the current state of the project.

See https://gist.github.com/holgerbrandl/e85f3b3e73de560be45fefa706d1234c

**Comment by deviant-studio** [comment]
Hmm. Interesting. Did you test csv parsing also?
What is `sd` column?
Btw TableSaw already migrated to Univocity. And looks like they are happy :)
https://github.com/jtablesaw/tablesaw/issues/284

**Comment by holgerbrandl** [comment]
sd == standard deviation. See https://github.com/holgerbrandl/kutils/blob/master/src/main/kotlin/de/mpicbg/scicomp/kutils/MicroBenchmark.kt#L54

I just tried tsv so far. Maybe there's so much overhead because `krangl` guesses types and so on? But I would not know how to separate this out.
I guess I keep the benchmark code as a reference and may do a more exhaustive benchmarking once I compared performance more high-level (e.g. between jtablesaw and krangl).
