### ISSUE TITLE
GroupBy HashCode collision

### ISSUE THREAD

**Issue by nwoike** [holgerbrandl/krangl#75]
I believe I am seeing rows being filtered unexpectedly from dataFrames when calling `distinct` but wanted to verify I am not misusing the library.

```
@Test
fun `distinct avoids hashCode collision`() {
    val dataFrame = dataFrameOf("a", "b", "c")(
        3, 263, 5,
        3, 325, 6,
        5, 201, 1,
        5, 263, 2,
        5, 265, 3,
        5, 325, 4
    )

    assertEquals(dataFrame.rows.toList(), dataFrame.distinct("a", "b").rows.toList())
}
```

Should this test pass?

```
dataFrame.distinct("a", "b").print()

A DataFrame: 4 x 3
    a     b   c
1   3   263   5
2   3   325   6
3   5   265   3
4   5   325   4
```

I believe this [line](https://github.com/holgerbrandl/krangl/blob/master/src/main/kotlin/krangl/SimpleDataFrame.kt#L288) in `SimpleDataFrame` is the culprit.

Something naive like the follow seems to work.

```
groupCols.rowData().map { it.joinToString(":").hashCode() }
```

**Example hashCodes**
```
println(listOf(3, 263).hashCode())
println(listOf(5, 201).hashCode())
println(listOf(3, 325).hashCode())
println(listOf(5, 263).hashCode())

// 1317
// 1317
// 1379
// 1379
       
println(arrayOf(3, 263).hashCode())
println(arrayOf(5, 201).hashCode())
println(arrayOf(3, 325).hashCode())
println(arrayOf(5, 263).hashCode())

// 411631404
// 897913732
// 1688019098
// 1792845110
```

**Comment by holgerbrandl** [comment]
Very well spotted. I'm still unsure if it's more a platform issue or a bug in krangl. You have greatly narrowed down to 
```
println(listOf(3, 263).hashCode())
println(listOf(5, 201).hashCode())
```
I wonder why this would give the same hash?! Naively, I assumed that hashcode collisions would be super rare but it seems they are not. I've asked in the kotlin slack for guidance, see https://kotlinlang.slack.com/archives/C0B8Q383C/p1565221454016900. Let's see what they say in order to develop a fix.

**Comment by holgerbrandl** [comment]
So it seems (see slack thread)  there is no way to avoid working with the complete grouping tuples. 

So to fix the issue, we will need to use `rowHashes: List<List<Any?>` instead of `rowHashes: List<Int>` to overcome this issue. We may also want to rename it, because its no long a hash. Maybe we could use a type-alias here to keep it readable?

I still wonder how this will affect performance.

**Comment by holgerbrandl** [comment]
The fix was more fun than anticipated by using a typealias for the grouping tuple instead of the hashcode-int. :-). Thanks again, for reporting the issue.
