### ISSUE TITLE
Adding Rows: Clearer/More Intuitive API?

### ISSUE THREAD

**Issue by CrystalLord** [holgerbrandl/krangl#76]
I posted this in the gitter chat, but it seemed quite dead.

I have a relatively simple question -- what is the simplest way to append rows to DataFrames? I saw issue #51 which is highly relevant, but I wasn't particularly satisfied with the answer.

In short what I'm trying to do: I want Pandas' append functionality: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html or dplyr's newer `add_row` functionality.

I understand DataFrames are immutable, so I'd ultimately be creating a new DataFrame in the end. However, the only way I've seen so far to create such a DataFrame is to create a row iterable, and feed that into another dataFrameOf like so:

```kotlin
val frame: DataFrame = dataFrameOf("Col1", "Col2") (
    "A", "B"
)

val newFrame: DataFrame = dataFrameOf(
    frame.rows + sequenceOf(mapOf(Pair("Col1", "C"), Pair("Col2", "D")))
)
/**
 * A DataFrame: 2 x 2
 *     Col1   Col2
 * 1      A      B
 * 2      C      D
*/
```

This seems particularly ugly, why not have an `addRow(row: DataFrameRow)` or `addRows(row: Iterable<DataFrameRow>)` method? Just be extremely explicit that it conducts a full copy.

At the very least, explicitly including how to add rows into the documentation would be really helpful.

**Comment by holgerbrandl** [comment]
Indeed, there is no built-in API yet to add rows. Currently, there is just `bindRows` to combine data-frames.  But it's fairly simple to add rows to:

```
var df = emptyDataFrame()

fun DataFrame.addRows(vararg someRows: DataFrameRow): DataFrame =
        bindRows(this, dataFrameOf(listOf(*someRows)))

val row: DataFrameRow = mapOf("foo" to "bar", "bla" to 1)

df = df.addRows(row, row, row)

df.print()
```
Depending on your prefs, you don't even need the helper method.  What do you think?

For efficiency `DataFrame.Companion.fromRecords(records: Iterable<T>, mapping: (T) -> DataFrameRow)` would be the much better choice though.

**Comment by CrystalLord** [comment]
I actually did end up making such an extension for this, since you're correct: it's very simple! But I swore there must have been a better way, and I had missed it.

I understand the efficiency is quite poor, but in my case I only needed to append a constant number of rows to the end generated from other CSVs which absolutely had to be loaded later.

Perhaps the best solution would be documentation on how to do such a thing, and explaining the API decision? Searching in the wikibook for what I would assume to be basic functionality gives zero results, which made me really question my sanity for a bit. 

I would be happy to contribute a PR for the docs if you'd be up for reviewing them. Or just adding that exact addRows method you provide above, with an explanation of why it's terribly inefficient ;)

**Comment by holgerbrandl** [comment]
The API is very much in flux, so there is no built-in method for this usecase yet. Feel welcome to contribute it. Since `DataFrameRow` has a very loosely defined type signature, the docs should make clear if it checks for column consistency or would fill up empty cells with NA in case of differing key-sets in `DataFrameRow`. Not sure which one is better, and there does not seem to be a clear consensus see https://stackoverflow.com/questions/42887217/difference-between-rbind-and-bind-rows-in-r

To avoid endless rewrapping of the data in the internal implementation we may want to use `DataFrame.Companion.fromRecords` as argued above.

**Comment by CrystalLord** [comment]
Added a PR at #77 . You'll still need to update the non-autogenerated docs to accommodate. I don't think I can do that on my end.

**Comment by CrystalLord** [comment]
Side note:

I would like to add that the test suite still fails because any tests that use the `flightData` fixture give me GC or OoM exceptions, even when setting a very large heap size. Is the `flightData` perhaps too big for Krangl?

**Comment by holgerbrandl** [comment]
I never had any issues with processing flightData. What are your JVM memory settings when running the tests?

**Comment by holgerbrandl** [comment]
Interesting and strange.

**Comment by holgerbrandl** [comment]
I took the liberty to rework the PR. 
* I renamed it to `bindRows` for consistency with the other `bindRows` and `bindCols`
* Grouping is now discarded because there is not consistent way to do so (just imagine 2 differently grouped tables being combined, which grouping should be picked). 
* The option to drop new columns was dropped since the a simple `foo.bindRows(bar).select(foo.names)` does the trick
* mapped the implementation to the existing `bindRows` which also covers `AnyCol` (in order to reduce the code places where we need to do when over all supported column types.
* No exception is thrown if colums don't match, but missing cells are simply filled with `NA`

I've updated tests and examples to reflect these changes in method contract.

**Comment by holgerbrandl** [comment]
> since they named theirs add_row rather than bind_rows).

Great that we can speak `dplyr` here, which is my reference when building krangl. Simply due to the fact that an insane amount of thought and manpower has condensed into dplyr's API, so it will be hard to do any better imho. Clearly, we use a different language, so not all constructs can be translated 1 to 1.

Concerning, the naming, I'm also a bit of unease: For an extension function df.addRows would be more natural than bindRows, however bindRows(df1, df2) seems more natural than addRows(d1, d2). Interesting, may we should call it `addRows` `addCols`  if its an extension, and `bind*` otherwise? Or is this too confusing already?

> Hmm, isn't the creation of a new DataFrame for the vararg case considerably slower now*? 

That's imho pure speculation. just god knows what's happening when the compiler and jit go through the code. I personally try to keep the implementation as simple as possible, unless profiling data proves the design to be wrong.

**Comment by holgerbrandl** [comment]
Uh, forgot to ask, what do you mean with 

>  as long as the manual highlights it existing.

?
