### ISSUE TITLE
Continue peeking until we hit the first/N non-NA values for column type detection

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/krangl#8]
See kplyr.peekCol

**Comment by LeanderG** [comment]
Should it also be possible to specify your own NA values when loading from a CSV/TSV file? Similar to how [readr](http://readr.tidyverse.org/reference/read_delim.html) does it with the `na` option? I don't think `quoted_na` can be implemented easily though.

**Comment by holgerbrandl** [comment]
Sure it should have such an option. :-) Feel welcome to provide a PR or try to be patient until I find some minutes to fix it later this week.
I think `quoted_na` could be implemented easily as well. We just need to make sure to have good test coverage for all those reader configurations.

**Comment by LeanderG** [comment]
I can provide a PR. I don't know how to implement `quoted_na` because the [csvParser](https://github.com/holgerbrandl/krangl/blob/22f26b51983afc77639cd42f4f9a8d8fc5988e93/src/main/kotlin/krangl/TableIO.kt#L73-L75) removes surrounding quotes from strings. Also I can't find an option in [CSVFormat](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html) to remove surrounding quotes.

**Comment by holgerbrandl** [comment]
That's a very good question. Since most users are most likely not familiar with `readr` I think it may be better to simply provide a `CSVFormat`. Once the API has consolidated more we could make them more explicit if needed. By doing so the user can already specify a custom NA via `CSVFormat.withNullString`.

What do you think?

**Comment by LeanderG** [comment]
Sounds good to me. I created a pull request. #33
